sudo: false
language: node_js
node_js:
  - "7"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
    firefox: latest-esr
script:
  - npm run build
  - npm test
  - npm run codecov